#!/bin/sh
STATE="$(bluetoothctl -- show | grep Powered | awk '{ print $2 }')"
if [ $STATE == "yes" ]; then
	bluetoothctl -- power off
	sudo rfkill block bluetooth
	notify-send "Bluetooth" "Powered off"
else
	sudo rfkill unblock bluetooth
	sleep 1
	bluetoothctl -- power on
	notify-send "Bluetooth" "Powered on"
fi
pkill -RTMIN+12 dwmblocks
