#!/bin/sh

# get hostname
HOST="$(uname -n)"

# generate an ssh key using the most secure algorithm (ed25519)
KEYFILE="${HOME}/.ssh/${HOST}.key"
ssh-keygen -t ed25519 -f "$KEYFILE" -C "${USER}@${HOST}" -N ''

# add the newly generated ssh key to our agent
eval $(ssh-agent)
ssh-add "$KEYFILE" 
