#!/bin/sh
xrandr --output DisplayPort-0 --primary --mode 3440x1440 --rate 144
#--pos 0x352 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --mode 2560x1440 --rate 144 --pos 3440x0 --rotate right --output HDMI-A-0 --off
