#!/usr/bin/env python

# gets a random wallpaper from wallhaven

from bs4 import BeautifulSoup
import requests
import random
import os


def save_image(image_url: str):
    image_response = requests.get(image_url)
    image_response.raise_for_status()

    filepath = f'/home/{os.environ["USER"]}/.wallpaper'
    with open(filepath, "wb") as f:
        f.write(image_response.content)

    os.system(f"feh --no-fehbg --bg-fill '{filepath}'")


def wallhaven():
    response = requests.get(
        "https://wallhaven.cc/search",
        params={
            "categories": "010",
            "purity": "110",
            "atleast": "3440x1440",
            "ratios": "landscape",
            "topRange": "3M",
            "sorting": "toplist",
            "order": "desc",
            "page": random.randint(1, 50),
        },
    )
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "lxml")

    thumbs = [t.attrs["data-wallpaper-id"] for t in soup.select(".thumb")]
    data_id = random.choice(thumbs)

    wp_response = requests.get(f"https://wallhaven.cc/w/{data_id}")
    wp_soup = BeautifulSoup(wp_response.text, "lxml")
    wp = wp_soup.select_one("#wallpaper")
    image_url = wp.attrs["src"]
    save_image(image_url)


if __name__ == "__main__":
    wallhaven()
