#!/usr/bin/env python

# gets a random ultrawide wallpaper from pexels.com

import requests
import random
import os

API_KEY = os.environ["PEXELS_API_KEY"]

q = "wallpaper"
page = random.randint(1, 1000)

response = requests.get(
    f"https://api.pexels.com/v1/search?query={q}&per_page=1&page={page}&orientation=landscape&size=large",
    headers={
        "Authorization": API_KEY,
    },
)

data = response.json()

image_url = data["photos"][0]["src"]["original"]

image_response = requests.get(image_url)

image_response.raise_for_status()

filepath =f'/home/{os.environ["USER"]}/.wallpaper' 
with open(filepath, 'wb') as f:
    f.write(image_response.content)

os.system(f"feh --no-fehbg --bg-fill '{filepath}'")
