#!/bin/sh
if iw dev | grep -q ssid; then
	DEVICE=$(iw dev | grep Interface | cut -d ' ' -f 2)
	SSID="$(iw dev $DEVICE info | grep ssid | cut -d ' ' -f 2)"
	echo " $SSID"
else
    echo "$(status-airplane-mode)"
fi
