#!/usr/bin/env bash

ICON_CHARGING=
ICON=

STATUS="$(acpi -b | grep -v " 0%," | head -n 1)"
PERCENTAGE="$(echo $STATUS | cut -d ',' -f 2)"
TIME_REMAINING=" |$(echo $STATUS | cut -d ',' -f 3 | cut -d ':' -f 1,2)"

if [[ "$TIME_REMAINING" != *":"* ]]; then
    TIME_REMAINING=""
fi

if [ "$(echo $STATUS | cut -d ' ' -f 3)" == "Charging," ]; then
    echo "$ICON_CHARGING$PERCENTAGE$TIME_REMAINING"
else
    echo "$ICON$PERCENTAGE$TIME_REMAINING"
fi
