#!/usr/bin/env bash

# uses xcolor to pick any color from the screen
# and copies the hex code to the clipboard

selectedcolor="$(xcolor | tr -d '[:space:]' | tr -d '#')"
echo "$selectedcolor" | xclip -selection clipboard
echo "#$selectedcolor"
notify-send "Color picked" "#$selectedcolor"
