name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            builders = @/etc/nix/machines
            max-substitution-jobs = 128
            http-connections = 128

      - name: Initialize attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: "https://attic.joinemm.dev"
          cache: "cache"
          token: '${{ secrets.ATTIC_AUTH_TOKEN }}'
          skip-push: true

      - name: Configure remote builders
        run: |
          sudo sh -c "umask 377; echo '${{ secrets.BUILDER_SSH_KEY }}' >/etc/nix/id_builder_key"

          sudo sh -c "echo 'ssh://github@hetzarm.vedenemo.dev aarch64-linux /etc/nix/id_builder_key 20 1 nixos-test,benchmark,big-parallel,kvm - -' >/etc/nix/machines"
          sudo sh -c "echo 'hetzarm.vedenemo.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILx4zU4gIkTY/1oKEOkf9gTJChdx/jR3lDgZ7p/c7LEK' >>/etc/ssh/ssh_known_hosts"
          
          sudo sh -c "echo 'ssh://github@builder.vedenemo.dev x86_64-linux,i686-linux /etc/nix/id_builder_key 16 1 kvm,benchmark,big-parallel,nixos-test - -' >>/etc/nix/machines"
          sudo sh -c "echo 'builder.vedenemo.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSI8s/wefXiD2h3I3mIRdK+d9yDGMn0qS5fpKDnSGqj' >>/etc/ssh/ssh_known_hosts"


      - name: Build packages
        run: nix run github:Mic92/nix-fast-build -- --flake ".#packages" --skip-cached --no-nom --attic-cache cache --result-format json --result-file result.json

      - name: View results
        run: cat result.json | jq

